SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Passwords](
	[passId] [int] IDENTITY(1,1) NOT NULL,
	[passUserId] [int] NOT NULL,
	[passPassword] [varchar](45) NOT NULL,
	[passDateChange] [datetime] NOT NULL,
 CONSTRAINT [pk_passId] PRIMARY KEY CLUSTERED 
(
	[passId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Passwords]  WITH CHECK ADD  CONSTRAINT [fk_userId] FOREIGN KEY([passUserId])
REFERENCES [dbo].[Users] ([userId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Passwords] CHECK CONSTRAINT [fk_userId]
GO
